.TH "mainwindow.cpp" 3 "Version 1.0.0" "netCom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'mainwindow\&.h'\fP
.br
\fR#include '\&./ui_mainwindow\&.h'\fP
.br
\fR#include 'udpbase\&.h'\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QFileDialog>\fP
.br
\fR#include <QNetworkInterface>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for netCom from the source code\&.
