.TH "MainWindow" 3 "Version 1.0.0" "netCom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBmainwindow\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fRnullptr\fP)"

.PP
Definition at line \fB9\fP of file \fBmainwindow\&.cpp\fP\&.
.PP
References \fBMainWindow()\fP\&.
.PP
Referenced by \fBMainWindow()\fP\&.
.SS "MainWindow::~MainWindow ()"

.PP
Definition at line \fB31\fP of file \fBmainwindow\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for netCom from the source code\&.
