.TH "tcpclient.h" 3 "Version 1.0.0" "netCom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcpclient.h
.SH SYNOPSIS
.br
.PP
\fR#include <QObject>\fP
.br
\fR#include <QTcpSocket>\fP
.br
\fR#include <QTcpServer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTCPClient\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for netCom from the source code\&.
