UDPBase
NAME
UDPBase
SYNOPSIS
#include <udpbase.h>
Inherits QObject.
Public Slots
bool isError (const QHostAddress &address, quint16 port)
void Read ()
void Send (const QString &address, quint16 port, const QByteArray &data)
Signals
void newMessage (QByteArray data, QHostAddress sender, quint16 senderPort)
Public Member Functions
UDPBase (QObject *parent=nullptr)
bool Bind (QHostAddress addr, quint16 port)
void Unbind ()
Detailed Description
Definition at line 7 of file udpbase.h.
Constructor & Destructor Documentation
UDPBase::UDPBase (QObject * parent = nullptr) [explicit]
Definition at line 3 of file udpbase.cpp.
Member Function Documentation
bool UDPBase::Bind (QHostAddress addr, quint16 port)
Definition at line 8 of file udpbase.cpp.
References isError(), and Read().
bool UDPBase::isError (const QHostAddress & address, quint16 port) [slot]
Definition at line 63 of file udpbase.cpp.
Referenced by Bind(), and Send().
void UDPBase::newMessage (QByteArray data, QHostAddress sender, quint16 senderPort) [signal]
Referenced by Read().
void UDPBase::Read () [slot]
Definition at line 42 of file udpbase.cpp.
References newMessage().
Referenced by Bind(), and Unbind().
void UDPBase::Send (const QString & address, quint16 port, const QByteArray & data) [slot]
Definition at line 34 of file udpbase.cpp.
References isError().
void UDPBase::Unbind ()
Definition at line 25 of file udpbase.cpp.
References Read().
Author
Generated automatically by Doxygen for netCom from the source code.